#pragma once
/*
 * tcp_program_bpf.h -- the TCP program's eBPF half, in generated shape.
 *
 * Read as generated code, like the control path's mtp/tcp_program.h. This file
 * holds what the compiler emits for the sites that run in eBPF: the flow id as
 * the packet carries it, the parser that builds it, and the context store
 * instantiated over TCP's own map with TCP's own key type.
 *
 * Ported so far:  the ingress flow id, its parser, the context store, and the
 *                 RX event processing (tcp_ack + tcp_data), and the TX site
 *                 (app_send's gen_seg, plus the two dummy-packet events).
 */

#include "mtp_target_bpf.h"   /* same directory */

/* ------------------------------------------------------------------ *
 * flow_id tcp_fid : (uint32, uint32, uint16, uint16)
 *
 * The eBPF side's id is `struct ebpf_flow_tuple` (intf_ebpf.h:190-195), which is
 * the SAME four values as the control path's flow_tuple in a different field
 * order and a different byte order. Two representations of one program-level
 * flow id, because the two sites keep their state in different containers -- a
 * target detail the program never sees.
 * ------------------------------------------------------------------ */
typedef struct ebpf_flow_tuple tcp_fid_bpf;

/*
 * net_parser: the id of the flow this packet belongs to, as seen from THIS host.
 * Host byte order, because that is what the map's keys are in.
 */
static __always_inline void tcp_fid_of_pkt_bpf(const struct iphdr *iph,
                                               const struct tcphdr *tcph,
                                               tcp_fid_bpf *out)
{
    out->local_ip    = bpf_ntohl(iph->daddr);
    out->remote_ip   = bpf_ntohl(iph->saddr);
    out->local_port  = bpf_ntohs(tcph->dest);
    out->remote_port = bpf_ntohs(tcph->source);
}

/* The context store for tcp_ctx's eBPF half (storage class (a)). */
MTP_DEFINE_CTX_STORE(tcp_bpf, tcp_fid_bpf, struct bpf_tcp_conn, bpf_tcp_conn_map)

/*
 * Which event is this packet?
 *
 * The classification MTP puts in the parser, and eTran already had as a guard:
 * SYN, SYN-ACK and RST are not fast-path events at all -- they are redirected to
 * the control path, where the ported tcp_syn / tcp_synack / tcp_rst processors
 * handle them. Everything else is an ACK and/or data, which is one call into
 * eTran's tcp_rx_process until those two events are split out.
 */
static __always_inline bool tcp_is_slow_path_event(const struct tcphdr *tcph)
{
    return is_tcp_syn(tcph) || is_tcp_syn_ack(tcph) || is_tcp_rst(tcph);
}

/* ------------------------------------------------------------------ *
 * THE RX PROCESSORS ARE GENERATED NOW.
 *
 * What stood here was the donor's RX fast path with its locals lifted into a
 * scratchpad and its processors extracted by hand -- about 270 lines. It is
 * replaced by the compiler's output for the same program, from mtp/tcp.mtp,
 * regenerated by mtp/generate.sh and committed under gen/.
 *
 * The generated processors take eTran's OWN structs -- bpf_tcp_conn for the
 * eBPF @placement group, bpf_cc for the shared congestion group -- because
 * --ctx-type told the backend those exist. So this is a substitution and not a
 * bridge: no cast, no copy, no adapter in the hot path. Anything measured here
 * is the generated code, not the cost of connecting it.
 *
 * WHAT IS STILL HAND-WRITTEN, and why it is not a gap:
 *   - the packet metadata (`data_meta->rx.*`) that drives the AF_XDP redirect.
 *     It is a projection of the scratchpad and of the state before the chain
 *     ran, so the target computes it below; a program has no business naming a
 *     descriptor ring.
 *   - post_data and send_ack, which are the target's epilogue.
 * ------------------------------------------------------------------ */
#include "gen/prog.h"
#include "gen/prog_proc_bpf.h"
#include "gen/prog_dispatch_bpf.h"

/*
 * The metadata the redirect needs, derived after the chain from the scratchpad
 * and from where the stream stood before it. rx_pos has to be computed against
 * the PRE-chain position, which is why they are captured by the caller.
 */
static __always_inline void mtp_rx_meta(struct bpf_tcp_conn *c, struct meta_info *data_meta,
                                        struct tcp_scratch *s, __u32 pos0, __u32 seq0)
{
    data_meta->rx.poff = s->payload_off;
    data_meta->rx.plen = s->payload_len;

    __u32 pos = pos0 + (s->seq - seq0);
    if (pos >= c->rx_buf_size)
        pos -= c->rx_buf_size;
    data_meta->rx.rx_pos = pos;

    /* Which of the three out-of-order outcomes happened is the PROGRAM's
     * knowledge -- it is the only thing here that cannot be derived -- so it
     * says so in the scratchpad and this only translates. */
    if (s->clear_ooo)     data_meta->rx.ooo_bump = OOO_CLEAR_MASK;
    else if (s->ooo_fin)  data_meta->rx.ooo_bump = OOO_FIN_MASK;
    else if (s->ooo_seg)  data_meta->rx.ooo_bump = OOO_SEGMENT_MASK;

    if ((c->rx_avail >> TCP_WND_SCALE) == 0)
        data_meta->rx.qid |= FORCE_RX_BUMP_MASK;
}

/* The epilogue both events share: it runs whether or not the chain completed. */
static __always_inline void post_data(struct bpf_tcp_conn *c, struct meta_info *data_meta,
                                      struct tcp_scratch *s)
{
    /* --- post_data (EVENT-DATA 1.3): the epilogue both events share ------- */
    /* redirect this packet to userspace */
    if (likely(s->rx_bump || s->tx_bump || s->go_back_pos || xsk_budget_avail(c)) || s->clear_ooo) {
        s->drop = false;
        
        data_meta->rx.xsk_budget_avail = xsk_budget_avail(c);
        xdp_log("xsk_budget_avail(%u)", data_meta->rx.xsk_budget_avail);
        if (s->tx_bump)
            data_meta->rx.ack_bytes = s->tx_bump;
        else if (unlikely(s->go_back_pos)) {
            xdp_log("go_back_pos(%u)", s->go_back_pos);
            data_meta->rx.go_back_pos = s->go_back_pos;
            data_meta->rx.go_back_pos |= RECOVERY_MASK;
        }

        if (!s->payload_len) {
            data_meta->rx.rx_pos = POISON_32;
            data_meta->rx.poff = POISON_16;
            data_meta->rx.plen = POISON_16;
            return;
        }

        if (unlikely(data_meta->rx.ooo_bump & OOO_FIN_MASK)) {
            /* piggyback s->rx_bump */
            data_meta->rx.ooo_bump |= s->rx_bump;
        }

    }

}

static __always_inline void send_ack(struct bpf_tcp_conn *c, struct tcp_scratch *s,
                                     bool ece, __u32 cpu)
{
    if (s->trigger_ack) {
        // TODO
        xdp_log("trigger_ack");
        #ifdef ACK_COALESCING
        // make verifier happy
        if (likely(cpu < MAX_CPU) && prev_conn[cpu] == NULL_CONN) {
            prev_conn[cpu] = c->cc_idx;
            prev_conn_li[cpu] = c->local_ip;
            prev_conn_lp[cpu] = c->local_port;
            prev_conn_ri[cpu] = c->remote_ip;
            prev_conn_rp[cpu] = c->remote_port;
            prev_conn_ece[cpu] |= ece;
        }
        #else
        if (likely(cpu < MAX_CPU && ack)) {
            enqueue_ack(c, ack, cpu, s->now, ece);
        }
        #endif
    }

}

static __always_inline int dispatch_tcp_rx(struct tcphdr *tcph, struct bpf_tcp_conn *c,
                                           __u32 pkt_len, struct meta_info *data_meta,
                                           bool ece, __u32 cpu)
{
    /* scratchpad_t tcp_scratch -- the values this event's processors pass to one
     * another. In the donor these were fifteen locals of one 290-line function;
     * naming them as a scratchpad is what makes the processor boundaries below
     * mean anything. */
    struct tcp_scratch s = {0};
    s.trigger_ack = false;
    s.drop        = true;
    s.payload_off = sizeof(struct ethhdr) + sizeof(struct iphdr) + sizeof(struct tcphdr) + TS_OPT_SIZE;
    s.payload_len = pkt_len - s.payload_off;
    s.seq         = bpf_ntohl(tcph->seq);
    s.ack_seq     = bpf_ntohl(tcph->ack_seq);

    struct tcp_timestamp_opt *ts_opt = (struct tcp_timestamp_opt *)(tcph + 1);
    #ifndef ACK_COALESCING
    struct bpf_tcp_ack *ack = NULL;
    #endif

    if (!rx_cached_ts[cpu])
        s.now = bpf_ktime_get_ns();
    else
        s.now = rx_cached_ts[cpu];

    /* trigger an ACK if there is payload (even if we discard it) */
    if (s.payload_len) {
        s.trigger_ack = true;

        #ifndef ACK_COALESCING
        __u32 prod = ack_prod[cpu];
        __u32 cons = ack_cons[cpu];

        // check if ack queue is full
        if (unlikely(cons == ((prod + 1) & (NAPI_BATCH_SIZE - 1)))) {
            xdp_log_err("ack queue is full");
        } else {
            ack = bpf_map_lookup_elem(&bpf_tcp_ack_map, &prod);
            if (unlikely(!ack))
                xdp_log_err("ack is NULL");
        }
        #endif
    }

    struct bpf_cc *cc = bpf_map_lookup_elem(&bpf_cc_map, &c->cc_idx);
    if (unlikely(!cc)) {
        xdp_log_panic("cc is NULL, BUG!!!");
        return XDP_DROP;
    }

    TCP_LOCK(c);
    

    /*
     * The processor chain. A processor returning false ends it -- eTran's
     *  -- and the epilogue runs regardless.
     *
     * THE ORDER IS THE DONOR'S AND IT IS NOT THE DOCUMENTS' ORDER. proc_window
     * and proc_rtt are tcp_ack processors and they run AFTER tcp_data's
     * sequence validation, so a packet with a bad sequence number never updates
     * the receive window even though the window is ACK state. Running the two
     * events' lists back to back would be a different program; see the comment
     * on the scratchpad above.
     */
    /* The two events this packet raises, built from the header once. */
    struct tcp_ack  ev_ack  = {0};
    struct tcp_data ev_data = {0};
    ev_ack.seq  = s.seq;   ev_ack.ack  = s.ack_seq;
    ev_ack.window = bpf_ntohs(tcph->window);
    ev_ack.ts_val = s.ts_val; ev_ack.ts_ecr = s.ts_ecr;
    ev_ack.payload_len = s.payload_len;
    ev_ack.ecn_ce = ece;
    ev_data.seq = s.seq;   ev_data.ack = s.ack_seq;
    ev_data.window = ev_ack.window;
    ev_data.ts_val = s.ts_val; ev_data.ts_ecr = s.ts_ecr;
    ev_data.payload_len = s.payload_len;
    ev_data.ecn_ce = ece;

    /* Where the stream stood before the chain, for the metadata below. */
    __u32 pos0 = c->rx_next_pos, seq0 = c->rx_next_seq;

    /*
     * THE DONOR'S ORDER, WITH THE DONOR'S EARLY EXITS -- and this is a TARGET
     * decision, not the program's.
     *
     * One segment raises tcp_ack and tcp_data together. The program declares
     * two chains and says nothing about how a target holding both at once
     * should schedule them, so the schedule is ours to pick, and we pick
     * eTran's: it interleaves them, and window and RTT do not update for a
     * packet whose sequence number was rejected.
     *
     * AN EARLIER VERSION RAN THE TWO DISPATCHES BACK TO BACK, and that was
     * wrong in a way the interleave test did not catch: that test compared the
     * two ORDERS but ran every processor in both, so it never modelled the
     * chain ENDING. The donor's `break` skips work; the generated dispatches
     * skip nothing. The program now carries `ack_ok` and `seg_ok` and every
     * processor that must not run guards on them -- which is how MTP says
     * "the chain is over" -- and the calls below are ordered to match.
     */
    proc_ack(&ev_ack, c, cc, &s);
    if (likely(s.ack_ok)) {
        proc_fast_retransmit(&ev_ack, c, cc, &s);
        proc_seq(&ev_data, c, &s);
        proc_ooo(&ev_data, c, &s);
        if (likely(s.seg_ok)) {
            proc_window(&ev_ack, c, &s);
            proc_rtt(&ev_ack, c, cc, &s);
            proc_recv(&ev_data, c, &s);
        }
    }
    mtp_rx_meta(c, data_meta, &s, pos0, seq0);

    post_data(c, data_meta, &s);
    send_ack(c, &s, ece, cpu);

    TCP_UNLOCK(c);

    return s.drop ? XDP_DROP : XDP_REDIRECT;
}

/* ------------------------------------------------------------------ *
 * scratchpad_t tcp_tx_scratch { ... }   -- app_send's processors share these.
 * ------------------------------------------------------------------ */
/* tcp_tx_scratch is generated now -- see gen/prog_blueprint.h. */

/*
 * dispatch: app_send -> { record_data, gen_seg }
 *
 * The XDP_EGRESS site (K2), which runs once per descriptor the application
 * submits. It is where a frame the application has already filled with payload
 * gets its TCP header, its sequence number, and its transmit decision -- the
 * return value IS the decision: XDP_TX now, XDP_REDIRECT into the timing wheel,
 * or XDP_PASS back to the application when the application has work to do.
 *
 * THIS SITE SERVES THREE EVENTS, not one, and the doc set does not say so. Two
 * of them arrive as DUMMY PACKETS -- frames with no payload sent purely to make
 * this program run, which is the mechanism the paper describes as "fake packets
 * with the event metadata" (appendix C):
 *
 *   FLAG_TO    the control path's retransmission timeout  -> gen_retransmit
 *   FLAG_SYNC  the application's window update            -> send_wnd_update
 *   neither    an actual segment to send                  -> gen_seg
 *
 * So a compiler targeting this backend has to know that one execution site is
 * the landing point for three events distinguished by a metadata flag, and that
 * two of them carry no packet at all. Marked in place, as with the RX path.
 */
/*
 * The three events this site serves, as three processors.
 *
 * A processor returns an XDP verdict, or MTP_TX_NEXT to say "not my event, try
 * the next one". That is the dispatch's selector: eTran distinguishes the three
 * by a metadata flag, and the flag tests stay inside the processors they select.
 *
 * THE LOCK IS NOT THE TARGET'S HERE, and that is deliberate. eTran acquires the
 * connection lock in the dispatch and each processor releases it -- but gen_seg
 * releases it PARTWAY THROUGH, before the timing-wheel insert, because that work
 * does not need the connection. MTP leaves state consistency to the target
 * (paper 4.1), and a target that owned locking uniformly would hold this lock
 * across the timing wheel and lengthen it on the hot send path. So the unlocks
 * stay exactly where the donor put them.
 */
#define MTP_TX_NEXT (-1)

static __always_inline int gen_retransmit(struct bpf_tcp_conn *c, struct bpf_cc *cc,
                                          struct meta_info *data_meta, struct tcp_tx_scratch *s)
{
    /* --- gen_retransmit (EVENT-TIMER-RTO 1.3): the RTO's dummy packet ----- */
    /* Timeout packet from slowpath, process it first */
    if (unlikely(data_meta->tx.flag & FLAG_TO)) {
        /* GENERATED: whether there is anything outstanding to resend. Where the
         * stream goes back to is the target's congestion control, which owns
         * the recovery point -- see fast_retransmit just below. */
        struct rto_timeout ev_to = {0};
        gen_retransmit(&ev_to, c, s);
        if (!s->tx_ok) {
            TCP_UNLOCK(c);
            xdp_egress_log("Timeout but no data to retransmit");
            return XDP_DROP;
        }
        data_meta->rx.go_back_pos = fast_retransmit(c, cc);
        // prepare to redirect to userspace
        data_meta->rx.qid = POISON_32;
        data_meta->rx.conn = c->opaque_connection;
        data_meta->rx.rx_pos = POISON_32;
        data_meta->rx.poff = POISON_16;
        data_meta->rx.plen = POISON_16;
        data_meta->rx.xsk_budget_avail = xsk_budget_avail(c);
        data_meta->rx.go_back_pos |= RECOVERY_MASK;
        data_meta->rx.ooo_bump = POISON_32;
        TCP_UNLOCK(c);
        // bpf_printk("Timeout triggers fast retransmission");
        return XDP_PASS; // redirect to userspace
    }

    return MTP_TX_NEXT;
}

static __always_inline int send_wnd_update(struct iphdr *iph, struct tcphdr *tcph,
                                           struct bpf_tcp_conn *c, void *data_end,
                                           struct meta_info *data_meta,
                                           struct tcp_tx_scratch *s)
{
    /* --- send_wnd_update (EVENT-APP-RECV 1.3) ----------------------------- */
    /* update receving buffer space */
    /* GENERATED: the window has moved, and whether that is worth a packet of its
     * own. Building the frame and choosing the verdict stay the target's. */
    {
        struct app_recv ev_rcv = {0};
        send_wnd_update(&ev_rcv, c, s);
    }

    /* --- the FLAG_SYNC dummy packet: a frame with no payload sent purely to
     *     make this site run. The paper's "fake packets with the event metadata"
     *     (appendix C). ------------------------------------------------------ */
    /* Pure sync packet from userspace, drop or send a extra window update */
    if (unlikely(data_meta->tx.flag & FLAG_SYNC)) {
        xdp_egress_log("pure ctrl signal");
        if (s->wnd_upd) {
            /* receive buffer freed up from empty, need to send out a window update, if
             * we're not sending anyways. */
            fill_tcp_hdr(iph, tcph, c, s->ref_ts, data_end, TCP_FLAG_ACK);
            fill_ip_hdr(iph, 0, false);
            TCP_UNLOCK(c);
            xdp_egress_log("Rxwnd is updated from empty to %u, send extra ack", min(c->rx_avail >> TCP_WND_SCALE, 0xFFFF));
            return XDP_TX;
        }
        TCP_UNLOCK(c);
        return XDP_DROP;
    }
    return MTP_TX_NEXT;
}

static __always_inline int gen_seg(struct iphdr *iph, struct tcphdr *tcph,
                                   struct bpf_tcp_conn *c, struct bpf_cc *cc,
                                   void *data_end, struct meta_info *data_meta,
                                   struct tcp_tx_scratch *s, __u32 cpu)
{

    // this is probably caused by fast retransmission as we reset the c->tx_next_pos
    // but there are pending packets in the queue, simply drop them
    /*
     * The guard and the state advance are BOTH generated, and both happen
     * below, in one call. The donor checks first and advances last; a generated
     * processor is one function, so the check comes with the advance and the
     * frame that fails it is built and then dropped. That costs work on a path
     * that already ends in XDP_DROP, and it is the alternative -- calling the
     * processor twice -- that would be wrong: it advances state.
     */

    __u32 avail = tcp_txavail(c);

    if (unlikely(avail < s->payload_len)) {
        // FIXME
        // bpf_printk("c->rx_remote_avail(%u), c->tx_sent(%u), c->tx_avail(%u), payload_len(%u)", 
        //     c->rx_remote_avail, c->tx_sent, c->tx_avail, s->payload_len);
        // bpf_printk("avail(%u) < payload_len(%u)", avail, s->payload_len);
    }

    __u64 desired_tx_ts = cc_get_desired_tx_ts(cc, s->ref_ts, s->payload_len);

    fill_tcp_hdr(iph, tcph, c, desired_tx_ts, data_end, 0);

    fill_ip_hdr(iph, s->payload_len, c->ecn_enable);

    /* GENERATED: everything a segment going out advances, and the consistency
     * check between where the application believes the stream is and where the
     * transport does. */
    struct app_send ev_snd = {0};
    ev_snd.len = s->payload_len;
    gen_seg(&ev_snd, c, cc, s);
    if (unlikely(!s->tx_ok)) {
        TCP_UNLOCK(c);
        return XDP_DROP;
    }

    // /*** NO CC ***/
    // TCP_UNLOCK(c);
    // // xdp_egress_log("Always bypass rate limiter");
    // return XDP_TX;
    
    #ifdef BYPASS_RL
    if (cc->rate >= LINK_BANDWIDTH && !nr_pkts_in_tw[cpu]) {
        // eRPC recommends to bypass rate limiter
        goto bypass_rl;
    }
    #endif

    #ifdef BYPASS_RL
    if ((!nr_pkts_in_tw[cpu] || c->tx_sent == s->payload_len) && desired_tx_ts <= s->ref_ts) {
        goto bypass_rl;
    }
    #endif

    TCP_UNLOCK(c);

    // bpf_printk("cc->rate(%lu)", cc->rate);

    __u32 key = cpu;
    struct timing_wheel *tw_map = bpf_map_lookup_elem(&tw_outer_map, &key);
    if (unlikely(!tw_map)) {
        log_panic("tw_map is NULL");
        return XDP_DROP;
    }

    __u32 idx = tw_insert(cpu, desired_tx_ts);
    if (unlikely(idx == POISON_32)) {
        log_panic("idx == POISON_32");
        return XDP_DROP;
    }
    // bpf_printk("TW idx(%u), tx_ts(%lu), (%u)", idx, desired_tx_ts, cc->rate);

    return bpf_redirect_map(tw_map, idx, 0);

#ifdef BYPASS_RL
bypass_rl:
    TCP_UNLOCK(c);
    xdp_egress_log("bypass rate limiter");
    return XDP_TX;
#endif
}

static __always_inline int dispatch_tcp_tx(struct iphdr *iph, struct tcphdr *tcph,
                                           struct bpf_tcp_conn *c,
                                           struct meta_info *data_meta, void *data_end)
{
    /* scratchpad_t tcp_tx_scratch -- app_send's processors share these. */
    struct tcp_tx_scratch s = {0};   /* generated: gen/prog_blueprint.h */
    s.rx_bump    = data_meta->tx.rx_bump;
    s.payload_len = data_meta->tx.plen;
    s.tx_pending = data_meta->tx.tx_pending;
    s.tx_pos     = data_meta->tx.tx_pos;
    s.ref_ts     = 0;
    s.wnd_upd    = false;

    __u32 cpu = bpf_get_smp_processor_id();
    if (unlikely(cpu >= MAX_CPU))
        return XDP_DROP;
    // optimization for timestamp
    if (!has_kick[cpu])
        s.ref_ts = bpf_ktime_get_ns();
    else
        s.ref_ts = tx_cached_ts[cpu];


    struct bpf_cc *cc = bpf_map_lookup_elem(&bpf_cc_map, &c->cc_idx);
    if (unlikely(!cc)) {
        xdp_log_panic("cc is NULL, BUG!!!");
        return XDP_DROP;
    }

    TCP_LOCK(c);


    /*
     * The selector. Each processor tests the flag that selects it and returns
     * MTP_TX_NEXT if it is not the one. gen_seg is last and always answers.
     *
     * Every one of them releases the lock this dispatch took -- see the note on
     * the processors above; gen_seg drops it partway through on purpose.
     */
    int v = gen_retransmit(c, cc, data_meta, &s);          /* FLAG_TO   */
    if (v != MTP_TX_NEXT)
        return v;

    v = send_wnd_update(iph, tcph, c, data_end, data_meta, &s);   /* FLAG_SYNC */
    if (v != MTP_TX_NEXT)
        return v;

    return gen_seg(iph, tcph, c, cc, data_end, data_meta, &s, cpu);
}
